### ISSUE TITLE
Debug log ?

### ISSUE THREAD

**Issue by warpdesign** [austin-----/vscode-twitter#1]
I have created a new Twitter app, configured all needed 4 keys in my user settings but nothing happens when clicking on Twitter icon and chosing "Home - Goto home timeline".

Is there a debug log somewhere ?

*Note*: it appears to be working: I was able to post a new status. But I don't see any timeline when chosing "Goto home timeline". Same goes when making a search: nothing happens.

**Comment by austin-----** [comment]
@warpdesign If you open the debug panel from 'Help -> Toggle Developer Tools', does it show any errors?

**Comment by warpdesign** [comment]
Yes.

[Plugin Host] Congratulations, your extension "vscode-twitter" is now active!
workbench.main.js:1602 [Plugin Host] Type: 1 selected
workbench.main.js:1602 [Plugin Host] Output omitted for a large object that exceeds the limits

[...]

[Plugin Host] Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Error

[...]

Plugin Host] Twitter buffer file: file://c%3A%5CUsers%5CNicolas%5CAppData%5CLocal%5CTemp%5CTwitter_HomeTimeline_4.md
workbench.main.js:1626 TypeError: Cannot set property 'vscTwitterShouldTogglePreview' of undefined: TypeError: Cannot set property 'vscTwitterShouldTogglePreview' of undefined
    at C:\Users\Nicolas\.vscode\extensions\austin.a-vscode-twitter\out\src\commands.js:33:64
    at Object.p [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:3663)
    at Object.__dirname.undefined.L.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:6825)
    at __dirname.undefined.t.Class.define._run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:8651)
    at __dirname.undefined.t.Class.define._completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:8092)
    at Object.p.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:11:17220)
    at process.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:19:9111)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)

**Comment by austin-----** [comment]
Thanks for the information. It looks like it is a Windows specific issue(haven't tried on Windows until now). Just made a fix and published a new version. Could you please give it a try and let me know how did it work for you?

**Comment by austin-----** [comment]
Please re-open if it is still an issue.

**Comment by warpdesign** [comment]
Seems to be fine now (version 0.3.5). Thank you.
